version: '3.7'
services:
  db:
    image: mariadb:10.4
    container_name: expenseapp-db-dev
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: expenseapp
    volumes:
     - type: volume
       source: mariadb-data
       target: /var/lib/mysql
       volume:
         nocopy: true

  adminer:
    image: adminer
    restart: on-failure
    container_name: expenseapp-adminer-dev
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    container_name: expenseapp-mailhog-dev
    ports:
     - "1025:1025"
     - "8025:8025"
    environment:
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_STORAGE: memory

  redis:
    image: redis:5-alpine
    restart: on-failure
    container_name: expenseapp-redis-dev
    ports:
      - "6379:6379"
    volumes:
     - type: volume
       source: redis-data
       target: /data
       volume:
         nocopy: true

volumes:
  mariadb-data:
    driver: local
    external: false
    name: expenseapp-mariadb-data-dev
  redis-data:
    driver: local
    external: false
    name: expenseapp-redis-data-dev
