"""empty message

Revision ID: 0aa66aaee68d
Revises: 5d06a74b853d
Create Date: 2019-04-08 22:41:58.895432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa66aaee68d'
down_revision = '5d06a74b853d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('vector', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'vector')
    # ### end Alembic commands ###
