"""empty message

Revision ID: 17501c13c377
Revises: e9658a4667d2
Create Date: 2019-09-15 19:23:14.697932

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '17501c13c377'
down_revision = 'e9658a4667d2'
branch_labels = None
depends_on = None
        
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_currencies',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'currency_id')
    )
    # ### end Alembic commands ###
    
    # ### data migration ###
    op.execute('''INSERT 
                    event_currencies 
                    (
                    event_id, 
                    currency_id
                    )
                  SELECT
                    temp.event_id, 
                    temp.currency_id
                  FROM
                    (SELECT event_id, currency_id FROM expenses WHERE event_id IS NOT NULL
                    UNION
                    SELECT event_id, currency_id FROM settlements WHERE event_id IS NOT NULL
                    UNION
                    SELECT id event_id, base_currency_id currency_id FROM events) temp''')
    # ### end of data migration ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_currencies')
    # ### end Alembic commands ###
