"""empty message

Revision ID: 19734506c0c6
Revises: 646224ad02e3
Create Date: 2019-08-19 20:57:17.098408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19734506c0c6'
down_revision = '646224ad02e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('fileshare_link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'fileshare_link')
    # ### end Alembic commands ###
