"""empty message

Revision ID: 2c836fbd7001
Revises: 4c282b07d0e5
Create Date: 2019-02-25 22:19:49.781673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c836fbd7001'
down_revision = '4c282b07d0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
