"""empty message

Revision ID: 3ec5bbe0a0a5
Revises: 5fa03c52298a
Create Date: 2020-02-28 00:01:03.996540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec5bbe0a0a5'
down_revision = '5fa03c52298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_account_guid', table_name='bank_account')
    op.create_index(op.f('ix_bank_account_guid'), 'bank_account', ['guid'], unique=True)
    op.drop_index('ix_currencies_guid', table_name='currencies')
    op.create_index(op.f('ix_currencies_guid'), 'currencies', ['guid'], unique=True)
    op.drop_index('ix_events_guid', table_name='events')
    op.create_index(op.f('ix_events_guid'), 'events', ['guid'], unique=True)
    op.drop_index('ix_expenses_guid', table_name='expenses')
    op.create_index(op.f('ix_expenses_guid'), 'expenses', ['guid'], unique=True)
    op.drop_index('ix_images_guid', table_name='images')
    op.create_index(op.f('ix_images_guid'), 'images', ['guid'], unique=True)
    op.drop_index('ix_messages_guid', table_name='messages')
    op.create_index(op.f('ix_messages_guid'), 'messages', ['guid'], unique=True)
    op.drop_index('ix_notifications_guid', table_name='notifications')
    op.create_index(op.f('ix_notifications_guid'), 'notifications', ['guid'], unique=True)
    op.drop_index('ix_posts_guid', table_name='posts')
    op.create_index(op.f('ix_posts_guid'), 'posts', ['guid'], unique=True)
    op.drop_index('ix_settlements_guid', table_name='settlements')
    op.create_index(op.f('ix_settlements_guid'), 'settlements', ['guid'], unique=True)
    op.drop_index('ix_tasks_guid', table_name='tasks')
    op.create_index(op.f('ix_tasks_guid'), 'tasks', ['guid'], unique=True)
    op.drop_index('ix_thumbnails_guid', table_name='thumbnails')
    op.create_index(op.f('ix_thumbnails_guid'), 'thumbnails', ['guid'], unique=True)
    op.drop_index('ix_users_guid', table_name='users')
    op.create_index(op.f('ix_users_guid'), 'users', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guid'), table_name='users')
    op.create_index('ix_users_guid', 'users', ['guid'], unique=False)
    op.drop_index(op.f('ix_thumbnails_guid'), table_name='thumbnails')
    op.create_index('ix_thumbnails_guid', 'thumbnails', ['guid'], unique=False)
    op.drop_index(op.f('ix_tasks_guid'), table_name='tasks')
    op.create_index('ix_tasks_guid', 'tasks', ['guid'], unique=False)
    op.drop_index(op.f('ix_settlements_guid'), table_name='settlements')
    op.create_index('ix_settlements_guid', 'settlements', ['guid'], unique=False)
    op.drop_index(op.f('ix_posts_guid'), table_name='posts')
    op.create_index('ix_posts_guid', 'posts', ['guid'], unique=False)
    op.drop_index(op.f('ix_notifications_guid'), table_name='notifications')
    op.create_index('ix_notifications_guid', 'notifications', ['guid'], unique=False)
    op.drop_index(op.f('ix_messages_guid'), table_name='messages')
    op.create_index('ix_messages_guid', 'messages', ['guid'], unique=False)
    op.drop_index(op.f('ix_images_guid'), table_name='images')
    op.create_index('ix_images_guid', 'images', ['guid'], unique=False)
    op.drop_index(op.f('ix_expenses_guid'), table_name='expenses')
    op.create_index('ix_expenses_guid', 'expenses', ['guid'], unique=False)
    op.drop_index(op.f('ix_events_guid'), table_name='events')
    op.create_index('ix_events_guid', 'events', ['guid'], unique=False)
    op.drop_index(op.f('ix_currencies_guid'), table_name='currencies')
    op.create_index('ix_currencies_guid', 'currencies', ['guid'], unique=False)
    op.drop_index(op.f('ix_bank_account_guid'), table_name='bank_account')
    op.create_index('ix_bank_account_guid', 'bank_account', ['guid'], unique=False)
    # ### end Alembic commands ###
