"""empty message

Revision ID: 5d06a74b853d
Revises: 668a3b8b991c
Create Date: 2019-04-07 15:45:39.011378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d06a74b853d'
down_revision = '668a3b8b991c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('extension', sa.String(length=8), nullable=True))
    op.add_column('thumbnails', sa.Column('extension', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('thumbnails', 'extension')
    op.drop_column('images', 'extension')
    # ### end Alembic commands ###
