"""empty message

Revision ID: 5fa03c52298a
Revises: 7c9f638d339f
Create Date: 2020-02-27 20:22:41.602111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa03c52298a'
down_revision = '7c9f638d339f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_bank_account_guid'), 'bank_account', ['guid'], unique=False)
    op.add_column('currencies', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_currencies_guid'), 'currencies', ['guid'], unique=False)
    op.add_column('events', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_events_guid'), 'events', ['guid'], unique=False)
    op.add_column('expenses', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_expenses_guid'), 'expenses', ['guid'], unique=False)
    op.add_column('images', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_images_guid'), 'images', ['guid'], unique=False)
    op.add_column('messages', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_messages_guid'), 'messages', ['guid'], unique=False)
    op.add_column('notifications', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_notifications_guid'), 'notifications', ['guid'], unique=False)
    op.add_column('posts', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_posts_guid'), 'posts', ['guid'], unique=False)
    op.add_column('settlements', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_settlements_guid'), 'settlements', ['guid'], unique=False)
    op.add_column('tasks', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_tasks_guid'), 'tasks', ['guid'], unique=False)
    op.add_column('thumbnails', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_thumbnails_guid'), 'thumbnails', ['guid'], unique=False)
    op.add_column('users', sa.Column('guid', sa.GUID(), nullable=True))
    op.create_index(op.f('ix_users_guid'), 'users', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guid'), table_name='users')
    op.drop_column('users', 'guid')
    op.drop_index(op.f('ix_thumbnails_guid'), table_name='thumbnails')
    op.drop_column('thumbnails', 'guid')
    op.drop_index(op.f('ix_tasks_guid'), table_name='tasks')
    op.drop_column('tasks', 'guid')
    op.drop_index(op.f('ix_settlements_guid'), table_name='settlements')
    op.drop_column('settlements', 'guid')
    op.drop_index(op.f('ix_posts_guid'), table_name='posts')
    op.drop_column('posts', 'guid')
    op.drop_index(op.f('ix_notifications_guid'), table_name='notifications')
    op.drop_column('notifications', 'guid')
    op.drop_index(op.f('ix_messages_guid'), table_name='messages')
    op.drop_column('messages', 'guid')
    op.drop_index(op.f('ix_images_guid'), table_name='images')
    op.drop_column('images', 'guid')
    op.drop_index(op.f('ix_expenses_guid'), table_name='expenses')
    op.drop_column('expenses', 'guid')
    op.drop_index(op.f('ix_events_guid'), table_name='events')
    op.drop_column('events', 'guid')
    op.drop_index(op.f('ix_currencies_guid'), table_name='currencies')
    op.drop_column('currencies', 'guid')
    op.drop_index(op.f('ix_bank_account_guid'), table_name='bank_account')
    op.drop_column('bank_account', 'guid')
    # ### end Alembic commands ###
