"""empty message

Revision ID: 646224ad02e3
Revises: 0aa66aaee68d
Create Date: 2019-07-15 22:50:15.621482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646224ad02e3'
down_revision = '0aa66aaee68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('rotate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'rotate')
    # ### end Alembic commands ###
