"""empty message

Revision ID: 668a3b8b991c
Revises: 09c65ac77c3a
Create Date: 2019-04-06 16:50:13.046902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668a3b8b991c'
down_revision = '09c65ac77c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('base_currency_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('exchange_fee', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'events', 'currencies', ['base_currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'exchange_fee')
    op.drop_column('events', 'base_currency_id')
    # ### end Alembic commands ###
