"""empty message

Revision ID: 6d324b095431
Revises: 1a9f08c4d593
Create Date: 2020-04-10 22:24:50.288756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d324b095431'
down_revision = '1a9f08c4d593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventusers', sa.Column('weighting', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    
    # ### data migration ###
    op.execute('''UPDATE 
	                    eventusers eu 
                  SET eu.weighting=1.0 where eu.weighting is null''')
    # ### end of data migration ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventusers', 'weighting')
    # ### end Alembic commands ###
