"""empty message

Revision ID: 7903a539dcf2
Revises: 3ec5bbe0a0a5
Create Date: 2020-03-28 11:01:23.967486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7903a539dcf2'
down_revision = '3ec5bbe0a0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_currencies', sa.Column('inCHF', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # ### data migration ###
    op.execute('''UPDATE 
	                    event_currencies ec 
                  SET ec.inCHF=(SELECT c.inCHF FROM currencies c WHERE c.id=ec.currency_id )''')
    # ### end of data migration ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_currencies', 'inCHF')
    # ### end Alembic commands ###
