"""empty message

Revision ID: 7c9f638d339f
Revises: 7d68282f1018
Create Date: 2020-02-27 20:08:40.211981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9f638d339f'
down_revision = '7d68282f1018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bank_account_user_id'), 'bank_account', ['user_id'], unique=False)
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=False)
    op.create_index(op.f('ix_expenses_event_id'), 'expenses', ['event_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=False)
    op.create_index(op.f('ix_log_date'), 'log', ['date'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_posts_event_id'), 'posts', ['event_id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_settlements_event_id'), 'settlements', ['event_id'], unique=False)
    op.create_index(op.f('ix_settlements_recipient_id'), 'settlements', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_settlements_sender_id'), 'settlements', ['sender_id'], unique=False)
    op.create_index(op.f('ix_thumbnails_image_id'), 'thumbnails', ['image_id'], unique=False)
    op.create_index(op.f('ix_thumbnails_name'), 'thumbnails', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnails_name'), table_name='thumbnails')
    op.drop_index(op.f('ix_thumbnails_image_id'), table_name='thumbnails')
    op.drop_index(op.f('ix_settlements_sender_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_recipient_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_event_id'), table_name='settlements')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_event_id'), table_name='posts')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_log_date'), table_name='log')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_event_id'), table_name='expenses')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_index(op.f('ix_bank_account_user_id'), table_name='bank_account')
    # ### end Alembic commands ###
