"""empty message

Revision ID: 7d68282f1018
Revises: 17501c13c377
Create Date: 2019-10-15 20:19:07.817335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d68282f1018'
down_revision = '17501c13c377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('module', sa.String(length=128), nullable=True),
    sa.Column('msg_type', sa.String(length=128), nullable=True),
    sa.Column('msg', sa.String(length=256), nullable=True),
    sa.Column('trace', sa.String(length=4096), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
