"""Migrate images to new File storage model

Revision ID: 8a6b6ed02c0f
Revises: 252734b648ed
Create Date: 2026-03-12 22:02:46.938654

"""
from alembic import op
import os
import hashlib
import mimetypes
from flask import current_app
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.sql import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a6b6ed02c0f'
down_revision = '252734b648ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('storage_backend', sa.String(length=32), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('hash_algorithm', sa.String(length=32), nullable=True),
    sa.Column('db_created_at', sa.DateTime(), nullable=True),
    sa.Column('db_updated_at', sa.DateTime(), nullable=True),
    sa.Column('db_created_by', sa.String(length=64), nullable=True),
    sa.Column('db_updated_by', sa.String(length=64), nullable=True),
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_guid'), ['guid'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_storage_backend'), ['storage_backend'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_storage_key'), ['storage_key'], unique=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_images_name'))
        batch_op.create_index(batch_op.f('ix_images_file_id'), ['file_id'], unique=False)
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])

    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_thumbnails_name'))
        batch_op.create_index(batch_op.f('ix_thumbnails_file_id'), ['file_id'], unique=False)
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'])

    # ==========================================================
    # BEGIN CUSTOM DATA MIGRATION
    # ==========================================================
    bind = op.get_bind()
    
    img_folder = current_app.config.get('IMAGE_IMG_PATH', 'images')
    timg_folder = current_app.config.get('IMAGE_TIMG_PATH', 'thumbnails')
    root_path = current_app.config.get('IMAGE_ROOT_PATH', os.path.join(current_app.root_path, 'static'))

    # 1. Migrate Images
    # We use raw SQL because the SQLAlchemy models have already changed in code
    images = bind.execute(text("SELECT id, name, extension, original_filename FROM images")).fetchall()
    for img in images:
        img_id, name, ext, orig_name = img
        name = name or ''
        ext = ext or ''
        
        # Ensure a unique storage key even if the database name is empty
        safe_name = name if name else f"orphaned_img_{img_id}"
        
        storage_key = f"{img_folder}/{safe_name}{ext}" 
        full_path = os.path.join(root_path, img_folder, f"{safe_name}{ext}")
        
        # Also ensure orig_name falls back to safe_name down in the execute block
        orig_name = orig_name or f"{safe_name}{ext}"
        
        file_size = 0
        file_hash = None
        mime_type = mimetypes.guess_type(orig_name or storage_key)[0] or 'application/octet-stream'
        
        # Read the physical file to calculate size and hash!
        if os.path.isfile(full_path):
            file_size = os.path.getsize(full_path)
            sha256 = hashlib.sha256()
            with open(full_path, 'rb') as f:
                while chunk := f.read(8192):
                    sha256.update(chunk)
            file_hash = sha256.hexdigest()
            
        # Insert File record
        bind.execute(
            text("""INSERT INTO files (original_filename, storage_backend, storage_key, mime_type, file_size, file_hash, hash_algorithm) 
                    VALUES (:orig, 'local', :key, :mime, :file_size, :file_hash, 'sha256')"""),
            {"orig": orig_name or f"{name}{ext}", "key": storage_key, "mime": mime_type, "file_size": file_size, "file_hash": file_hash}
        )
        
        # Query the newly generated File ID (DB-agnostic approach)
        file_id = bind.execute(
            text("SELECT id FROM files WHERE storage_key = :key"),
            {"key": storage_key}
        ).scalar()
        
        # Link File to Image
        bind.execute(
            text("UPDATE images SET file_id = :file_id WHERE id = :img_id"),
            {"file_id": file_id, "img_id": img_id}
        )

    # 2. Migrate Thumbnails
    thumbnails = bind.execute(text("SELECT id, name, extension FROM thumbnails")).fetchall()
    for thumb in thumbnails:
        thumb_id, name, ext = thumb
        name = name or ''
        ext = ext or ''
        
        safe_name = name if name else f"orphaned_thumb_{thumb_id}"
        
        storage_key = f"{timg_folder}/{safe_name}{ext}"
        full_path = os.path.join(root_path, timg_folder, f"{safe_name}{ext}")
        name = safe_name # Ensures the INSERT uses the safe_name
        
        file_size = 0
        file_hash = None
        mime_type = mimetypes.guess_type(storage_key)[0] or 'image/jpeg'
        
        if os.path.isfile(full_path):
            file_size = os.path.getsize(full_path)
            sha256 = hashlib.sha256()
            with open(full_path, 'rb') as f:
                while chunk := f.read(8192):
                    sha256.update(chunk)
            file_hash = sha256.hexdigest()
            
        bind.execute(
            text("""INSERT INTO files (original_filename, storage_backend, storage_key, mime_type, file_size, file_hash, hash_algorithm) 
                    VALUES (:orig, 'local', :key, :mime, :file_size, :file_hash, 'sha256')"""),
            {"orig": f"{name}{ext}", "key": storage_key, "mime": mime_type, "file_size": file_size, "file_hash": file_hash}
        )
        
        file_id = bind.execute(
            text("SELECT id FROM files WHERE storage_key = :key"),
            {"key": storage_key}
        ).scalar()
        
        bind.execute(
            text("UPDATE thumbnails SET file_id = :file_id WHERE id = :thumb_id"),
            {"file_id": file_id, "thumb_id": thumb_id}
        )
    # ==========================================================
    # END CUSTOM DATA MIGRATION
    # ==========================================================

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('extension')
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.drop_column('extension')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('extension', mysql.VARCHAR(length=8), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_thumbnails_file_id'))
        batch_op.create_index(batch_op.f('ix_thumbnails_name'), ['name'], unique=False)
        batch_op.drop_column('file_id')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('extension', mysql.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_images_file_id'))
        batch_op.create_index(batch_op.f('ix_images_name'), ['name'], unique=False)
        batch_op.drop_column('file_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_storage_key'))
        batch_op.drop_index(batch_op.f('ix_files_storage_backend'))
        batch_op.drop_index(batch_op.f('ix_files_guid'))
        batch_op.drop_index(batch_op.f('ix_files_file_hash'))

    op.drop_table('files')
    # ### end Alembic commands ###
