"""empty message

Revision ID: 9d75b4675a5c
Revises: 1fdbb8e40591
Create Date: 2020-08-30 21:30:01.279289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d75b4675a5c'
down_revision = '1fdbb8e40591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_account_ibfk_1', table_name='bank_account', type_='foreignkey')
    op.drop_index('ix_bank_account_guid', table_name='bank_account')
    op.drop_index('ix_bank_account_user_id', table_name='bank_account')
    op.drop_table('bank_account')
    op.add_column('eventusers', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('eventusers', sa.Column('address_suffix', sa.String(length=128), nullable=True))
    op.add_column('eventusers', sa.Column('bank', sa.String(length=64), nullable=True))
    op.add_column('eventusers', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('eventusers', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('eventusers', sa.Column('iban', sa.String(length=34), nullable=True))
    op.add_column('eventusers', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('eventusers', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventusers', 'zip_code')
    op.drop_column('eventusers', 'name')
    op.drop_column('eventusers', 'iban')
    op.drop_column('eventusers', 'country')
    op.drop_column('eventusers', 'city')
    op.drop_column('eventusers', 'bank')
    op.drop_column('eventusers', 'address_suffix')
    op.drop_column('eventusers', 'address')
    op.create_table('bank_account',
    sa.Column('db_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('db_updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('db_created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('db_updated_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('iban', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=34), nullable=True),
    sa.Column('bank', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('address_suffix', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('zip_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('guid', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bank_account_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_bank_account_user_id', 'bank_account', ['user_id'], unique=False)
    op.create_index('ix_bank_account_guid', 'bank_account', ['guid'], unique=True)
    # ### end Alembic commands ###
