"""empty message

Revision ID: bd8321557896
Revises: 9d75b4675a5c
Create Date: 2022-10-08 13:20:25.972662

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bd8321557896'
down_revision = '9d75b4675a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('db_created_at', sa.DateTime(), nullable=True),
    sa.Column('db_updated_at', sa.DateTime(), nullable=True),
    sa.Column('db_created_by', sa.String(length=64), nullable=True),
    sa.Column('db_updated_by', sa.String(length=64), nullable=True),
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_challenge_guid'), 'challenge', ['guid'], unique=True)
    op.create_index(op.f('ix_challenge_user_id'), 'challenge', ['user_id'], unique=False)
    op.create_table('credential',
    sa.Column('db_created_at', sa.DateTime(), nullable=True),
    sa.Column('db_updated_at', sa.DateTime(), nullable=True),
    sa.Column('db_created_by', sa.String(length=64), nullable=True),
    sa.Column('db_updated_by', sa.String(length=64), nullable=True),
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.LargeBinary(), nullable=True),
    sa.Column('public_key', sa.LargeBinary(), nullable=True),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('transports', sa.FIDO2Transports(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_credential_guid'), 'credential', ['guid'], unique=True)
    op.create_index(op.f('ix_credential_user_id'), 'credential', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credential_user_id'), table_name='credential')
    op.drop_index(op.f('ix_credential_guid'), table_name='credential')
    op.drop_table('credential')
    op.drop_index(op.f('ix_challenge_user_id'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_guid'), table_name='challenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###
