version: '3.7'
services:
  db:
    image: linuxserver/mariadb
    container_name: expenseapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: expenseapp
    networks:
     - expenseapp
    volumes:
     - type: volume
       source: mariadb-data
       target: /config
       volume:
         nocopy: true

  adminer:
    image: adminer
    restart: always
    container_name: expenseapp-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
     - expenseapp

  redis:
    image: redis:5
    restart: always
    container_name: expenseapp-redis
    networks:
     - expenseapp
    volumes:
     - type: volume
       source: redis-data
       target: /data
       volume:
         nocopy: true

  rq-worker:
    image: mredle/eexpenseapp:rpi
    restart: always
    entrypoint: rq
    command: ['worker', '-u', 'redis://redis:6379/0', 'expenseapp-tasks']
    container_name: expenseapp-rq-worker
    environment:
      SECRET_KEY: 'you-will-never-guess'
      DATABASE_URL: 'mysql+pymysql://user:password@db/expenseapp?charset=utf8mb4'
      MAIL_SERVER: 'mailhog'
      MAIL_PORT: '1025'
      MAIL_USE_TLS:
      MAIL_USERNAME: 'mailuser'
      MAIL_PASSWORD: 'mailpw'
      ADMIN_NOREPLY_SENDER: 'no-reply@expenseapp'
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'pw'
      ADMIN_EMAIL: 'admin@expenseapp'
      REDIS_URL: 'redis://redis:6379/0'
    networks:
     - expenseapp
    depends_on:
     - db
     - redis
    volumes:
     - type: volume
       source: expenseapp-data
       target: /home/flask_app/app/static
       volume:
         nocopy: false
         
  expenseapp:
    image: mredle/eexpenseapp:rpi
    restart: always
    container_name: expenseapp
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: 'you-will-never-guess'
      DATABASE_URL: 'mysql+pymysql://user:password@db/expenseapp?charset=utf8mb4'
      MAIL_SERVER: 'mailhog'
      MAIL_PORT: '1025'
      MAIL_USE_TLS:
      MAIL_USERNAME: 'mailuser'
      MAIL_PASSWORD: 'mailpw'
      ADMIN_NOREPLY_SENDER: 'no-reply@expenseapp'
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'pw'
      ADMIN_EMAIL: 'admin@expenseapp'
      REDIS_URL: 'redis://redis:6379/0'
    networks:
     - expenseapp
    depends_on:
     - rq-worker
     - db
     - redis
    volumes:
     - type: volume
       source: expenseapp-data
       target: /home/flask_app/app/static
       volume:
         nocopy: false
         
         
networks:
  expenseapp:
    driver: bridge
    name: expenseapp

volumes:
  expenseapp-data:
    driver: local
    external: false
    name: expenseapp-data
  mariadb-data:
    driver: local
    external: false
    name: expenseapp-mariadb-data
  redis-data:
    driver: local
    external: false
    name: expenseapp-redis-data
