version: '3.7'
services:
  db:
    image: mariadb:10.4
    container_name: expenseapp-db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: expenseapp
    networks:
     - expenseapp
    volumes:
     - type: volume
       source: mariadb-data
       target: /var/lib/mysql
       volume:
         nocopy: true

  postfix:
    image: catatnight/postfix
    restart: always
    container_name: expenseapp-postfix
    environment:
      maildomain: 'mail.example.com'
      smtp_user: 'mailuser:mailpw'
    networks:
     - expenseapp

  redis:
    image: redis:5-alpine
    restart: always
    container_name: expenseapp-redis
    networks:
     - expenseapp
    volumes:
     - type: volume
       source: redis-data
       target: /data
       volume:
         nocopy: true

  rq-worker:
    image: mredle/eexpenseapp:latest
    restart: always
    entrypoint: rq
    command: ['worker', '-u', 'redis://redis:6379/0', 'expenseapp-tasks']
    container_name: expenseapp-rq-worker
    environment:
      SECRET_KEY: 'you-will-never-guess'
      DATABASE_URL: 'mysql+pymysql://user:pw@db/expenseapp?charset=utf8mb4'
      MAIL_SERVER: 'postfix'
      MAIL_PORT: '25'
      MAIL_USE_TLS:
      MAIL_USERNAME: 'mailuser@mail.example.com'
      MAIL_PASSWORD: 'mailpw'
      ADMIN_NOREPLY_SENDER: 'no-reply@expenseapp'
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'pw'
      ADMIN_EMAIL: 'admin@expenseapp'
      REDIS_URL: 'redis://redis:6379/0'
    networks:
     - expenseapp
    depends_on:
     - db
     - redis
     - postfix
    volumes:
     - type: volume
       source: expenseapp-data
       target: /home/flask_app/app/static
       volume:
         nocopy: false
         
  expenseapp:
    image: mredle/eexpenseapp:latest
    restart: always
    container_name: expenseapp
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: 'you-will-never-guess'
      DATABASE_URL: 'mysql+pymysql://user:pw@db/expenseapp?charset=utf8mb4'
      MAIL_SERVER: 'postfix'
      MAIL_PORT: '25'
      MAIL_USE_TLS:
      MAIL_USERNAME: 'mailuser@mail.example.com'
      MAIL_PASSWORD: 'mailpw'
      ADMIN_NOREPLY_SENDER: 'no-reply@expenseapp'
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'pw'
      ADMIN_EMAIL: 'admin@expenseapp'
      REDIS_URL: 'redis://redis:6379/0'
    networks:
     - expenseapp
    depends_on:
     - rq-worker
     - db
     - redis
     - postfix
    volumes:
     - type: volume
       source: expenseapp-data
       target: /home/flask_app/app/static
       volume:
         nocopy: false
         
         
networks:
  expenseapp:
    driver: bridge
    name: expenseapp

volumes:
  expenseapp-data:
    driver: local
    external: false
    name: expenseapp-data
  mariadb-data:
    driver: local
    external: false
    name: expenseapp-mariadb-data
  redis-data:
    driver: local
    external: false
    name: expenseapp-redis-data
