version: '3.8'
services:
  db:
    image: mariadb:10.8
    container_name: expenseapp-db-dev
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping --silent']
      interval: 30s
      timeout: 10s
      retries: 4
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: expenseapp
    networks:
     - expenseapp
    volumes:
     - type: volume
       source: mariadb-data
       target: /var/lib/mysql
       volume:
         nocopy: true

  adminer:
    image: adminer
    restart: on-failure
    container_name: expenseapp-adminer-dev
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
     - expenseapp
     
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    restart: on-failure
    container_name: expenseapp-phpredisadmin-dev
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: redis
      REDIS_1_PORT: 6379
    depends_on:
      - redis
    ports:
      - "8081:80"
    networks:
     - expenseapp
     
  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    container_name: expenseapp-mailhog-dev
    ports:
     - "8025:8025"
    environment:
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_STORAGE: memory
    networks:
     - expenseapp

  redis:
    image: redis:7-alpine
    restart: on-failure
    container_name: expenseapp-redis-dev
    command: '--requirepass pw'
    networks:
     - expenseapp
    volumes:
     - type: volume
       source: redis-data
       target: /data
       volume:
         nocopy: true

  rq-worker:
    image: expenseapp:latest
    restart: on-failure
    entrypoint: rq
    command: ['worker', '-u', 'redis://:pw@redis:6379/0', 'expenseapp-tasks']
    container_name: expenseapp-rq-worker-dev
    environment:
      SECRET_KEY: 'you-will-never-guess'
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
      MYSQL_USER: 'user'
      MYSQL_PW: 'pw'
      MYSQL_DB: 'expenseapp'
      MAIL_SERVER: 'mailhog'
      MAIL_PORT: '1025'
      MAIL_USE_TLS:
      MAIL_USERNAME: 'mailuser'
      MAIL_PASSWORD: 'mailpw'
      ADMIN_NOREPLY_SENDER: 'no-reply@expenseapp'
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'pw'
      ADMIN_EMAIL: 'admin@expenseapp'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: pw 
    networks:
     - expenseapp
    depends_on:
     - db
     - redis
     - mailhog
    volumes:
     - type: volume
       source: expenseapp-data
       target: /home/flask_app/app/static
       volume:
         nocopy: false
         
  expenseapp:
    image: expenseapp:latest
    restart: on-failure
    container_name: expenseapp-dev
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: 'you-will-never-guess'
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
      MYSQL_USER: 'user'
      MYSQL_PW: 'pw'
      MYSQL_DB: 'expenseapp'
      MAIL_SERVER: 'mailhog'
      MAIL_PORT: '1025'
      MAIL_USE_TLS:
      MAIL_USERNAME: 'mailuser'
      MAIL_PASSWORD: 'mailpw'
      ADMIN_NOREPLY_SENDER: 'no-reply@expenseapp'
      ADMIN_USERNAME: 'admin'
      ADMIN_PASSWORD: 'pw'
      ADMIN_EMAIL: 'admin@expenseapp'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: pw 
    networks:
     - expenseapp
    depends_on:
     - rq-worker
     - db
     - redis
     - mailhog
    volumes:
     - type: volume
       source: expenseapp-data
       target: /home/flask_app/app/static
       volume:
         nocopy: false
         
         
networks:
  expenseapp:
    driver: bridge
    name: expenseapp-dev

volumes:
  expenseapp-data:
    driver: local
    external: false
    name: expenseapp-data
  mariadb-data:
    driver: local
    external: false
    name: expenseapp-mariadb-data
  redis-data:
    driver: local
    external: false
    name: expenseapp-redis-data
